let petName;
let petAge;
petName = "Danis";
petAge = 13;
console.log(petName);
console.log(petAge);
petName = "Rainys";
petAge = 10;
console.log(petName);
console.log(petAge);
const buildingAddress = "Ozo g. 12";
console.log(buildingAddress);